WINDOW_HEIGHT = 720
WINDOW_WIDTH = 1280

BOARD_MARGIN = int(5 * WINDOW_WIDTH / 100)  # 5% margin
BOARD_WIDTH = int(5*WINDOW_WIDTH / 6 - 2 * BOARD_MARGIN)
BOARD_HEIGHT = int(50 * WINDOW_HEIGHT / 100)  # 50% height

NB_SLOTS = 6
SLOT_MARGIN = int(5 * BOARD_HEIGHT // 100)
SLOT_WIDTH = int((BOARD_WIDTH - (NB_SLOTS + 1) * SLOT_MARGIN) / NB_SLOTS)
SLOT_HEIGHT = int((BOARD_HEIGHT - 3 * SLOT_MARGIN) / 2)

# Square the slots
SLOT_WIDTH = min(SLOT_HEIGHT, SLOT_WIDTH)
SLOT_HEIGHT = SLOT_WIDTH

# Readapt board to slots
BOARD_HEIGHT = SLOT_HEIGHT * 2 + SLOT_MARGIN * 3

TITLE_BAR_HEIGHT = int(5 * WINDOW_HEIGHT // 100)  # 5% height

UI_BUTTONS_HEIGHT = int(25 * WINDOW_HEIGHT // 100)  # 10% height
UI_BUTTONS_MARGIN = BOARD_MARGIN
UI_BUTTONS_WIDTH = BOARD_WIDTH

NB_CARDS_HAND = 5
